### ISSUE TITLE
dynamic support  example seems broken in 0.22

### ISSUE THREAD

**Issue by macdroid53** [mwganson/wirefilter#5]
Tying out the example file and get this when the height is changed:

`13:43:37  pyException: Traceback (most recent call last):
  File "/home/mac/SharedData/FC_common/pdwrapper.py", line 491, in execute
    shape = self.makeTipShape(fp)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/mac/SharedData/FC_common/pdwrapper.py", line 441, in makeTipShape
    base_shape = self.scaleXYZ(fp.TipBaseScaleXYZ, base_shape, fp.TipScaleCut)
                               ^^^^^^^^^^^^^^^^^^
<class 'AttributeError'>: 'FeaturePython' object has no attribute 'TipBaseScaleXYZ'
13:43:37  PDW_None: 'FeaturePython' object has no attribute 'TipBaseScaleXYZ'
`

**Comment by mwganson** [comment]
Thanks for the report.  Which file exactly?  Is this with WireFilter or PDWrapper?

**Comment by macdroid53** [comment]
Sorry, PDWrapper.

**Comment by mwganson** [comment]
No problem.  But which example file?  I think there are 4 of them in the examples folder.

**Comment by mwganson** [comment]
I found it.  The dynamic support example.  I have reproduced the error and will look into it.

**Comment by macdroid53** [comment]
Sorry...I guess I should have expanded my details:

https://github.com/mwganson/pdwrapper/blob/main/examples/pdwrapper_dynamic_support_example.FCStd

**Comment by mwganson** [comment]
I figured out the problem.  The PDW_None object was created with a newer version of PDWrapper, before the missing property was added in a later version.  I have updated that example file with a new object.  Bad work on my part, breaking existing models with an update.
